name: flow
description: A personal finance managing app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: "0.15.2+272"

environment:
    sdk: ">=3.8.0 <4.0.0"

dependencies:
    app_links: ^6.4.1
    app_settings: ^6.1.1
    archive: ^4.0.7
    auto_size_text: ^3.0.0
    charset: ^2.0.1
    connectivity_plus: ^7.0.0
    crop_image: ^1.0.16
    cross_file: ^0.3.4+2
    csv: ^6.0.0
    desktop_drop: ^0.6.1
    dotted_border: ^3.1.0
    file_picker: ^10.3.3
    file_saver: ^0.3.1
    fl_chart: ^1.1.1
    flutter:
        sdk: flutter
    flutter_contacts: ^1.1.9+2
    flutter_dynamic_icon_plus: ^1.3.1
    flutter_local_notifications: ^19.4.2
    flutter_localizations:
        sdk: flutter
    flutter_map: ^8.2.2
    flutter_markdown: ^0.7.4+2
    flutter_slidable: ^4.0.2
    flutter_staggered_grid_view: ^0.7.0
    flutter_timezone: ^5.0.0
    flutter_typeahead: ^5.2.0
    fuzzywuzzy: ^1.2.0
    geolocator: ^14.0.2
    go_router: ^16.2.4
    http: ^1.5.0
    icloud_storage: ^2.2.0
    image_picker: ^1.2.0
    in_app_review: ^2.0.11
    intl: ^0.20.2
    json_annotation: ^4.9.0
    latlong2: ^0.9.1
    local_auth: ^2.3.0
    local_hero: ^0.3.0
    local_settings: ^1.0.0
    logging: ^1.3.0
    logging_appenders: ^1.4.0+1
    material_symbols_icons: ^4.2873.0
    moment_dart: ^5.2.4
    objectbox: ^4.3.1
    objectbox_flutter_libs: ^4.3.1
    package_info_plus: ^8.3.1
    path: ^1.9.1
    path_provider: ^2.1.5
    pdf: ^3.11.3
    permission_handler: ^12.0.1
    pie_menu: ^3.3.0
    recurrence: ^0.3.0
    share_plus: ^12.0.0
    shared_preferences: ^2.5.3
    simple_icons: ^14.6.1
    smooth_page_indicator: ^1.2.1
    timezone: ^0.10.1
    toastification: ^3.0.3
    url_launcher: ^6.3.2
    uuid: ^4.5.1
    window_manager: ^0.5.1

dev_dependencies:
    build_runner: ^2.7.1

    flutter_launcher_icons: ^0.14.4

    flutter_lints: ^6.0.0
    flutter_test:
        sdk: flutter
    json_serializable: ^6.11.1
    objectbox_generator: ^4.3.1
    openai_dart: ^0.5.5
    test: ^1.25.15

flutter:
    generate: true
    uses-material-design: true

    config:
        disable-swift-package-manager: true

    assets:
        - assets/
        - assets/fonts/
        - assets/l10n/
        - assets/images/
        - assets/images/external/

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins-Regular.ttf
              - asset: assets/fonts/Poppins-Italic.ttf
                style: italic
              - asset: assets/fonts/Poppins-Medium.ttf
                weight: 500
              - asset: assets/fonts/Poppins-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Poppins-Bold.ttf
                weight: 700

objectbox:
    output_dir: objectbox
